version: "3.8"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.27
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: task_manager
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: root


  task-app:
    container_name: task-app
    image: prabodashan14/taskmanager:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_DB_NAME: task_manager
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3307
    depends_on:
      - mysqldb